const API = window.API_BASE || 'http://localhost:8080';
const state = { medicines: [], cart: [], user: JSON.parse(sessionStorage.getItem('user') || 'null'), activeMedicine: null };
const $ = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const money = value => `$${Number(value || 0).toFixed(2)}`;
const authHeaders = () => state.user?.token ? { Authorization: `Bearer ${state.user.token}` } : {};
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { ...authHeaders(), ...(options.headers || {}) } }); if (response.status === 401) { logout(false); throw new Error('Please sign in to continue.'); } const text = await response.text(); let data = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) throw new Error(data?.message || `Request failed (${response.status})`); return data; }
function toast(text, error = false) { const node = $('#toast'); node.textContent = text; node.className = `toast visible${error ? ' error' : ''}`; window.setTimeout(() => { node.className = 'toast'; }, 3600); }
function setView(view) { document.querySelectorAll('[data-page]').forEach(page => { page.hidden = page.dataset.page !== view; }); if (view === 'dashboard') loadOrders(); if (view === 'admin') loadAdminMedicines(); $('#hero').hidden = view !== 'catalog'; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function updateAuthUi() { const signedIn = Boolean(state.user); document.querySelectorAll('[data-auth-only]').forEach(node => { node.hidden = !signedIn; }); document.querySelectorAll('[data-admin-only]').forEach(node => { node.hidden = !signedIn || state.user.role !== 'ADMIN'; }); $('#auth-open').hidden = signedIn; $('#account-summary').textContent = signedIn ? `${state.user.email} · Your recent orders and fulfillment status.` : ''; $('#account-role').textContent = state.user?.role || 'CUSTOMER'; }
function renderCatalog() { const term = $('#search').value.trim().toLowerCase(); const category = $('#category').value; const sort = $('#sort').value; let items = state.medicines.filter(m => (!term || [m.name, m.description, m.category, m.manufacturer].some(value => String(value || '').toLowerCase().includes(term))) && (!category || m.category === category)); if (sort === 'price-low') items.sort((a, b) => a.price - b.price); if (sort === 'price-high') items.sort((a, b) => b.price - a.price); if (sort === 'stock') items.sort((a, b) => b.stock - a.stock); $('#catalog-empty').hidden = items.length > 0; $('#catalog').innerHTML = items.map(m => `<article class="product-card"><button class="product-image" data-detail="${m.id}" aria-label="View ${escapeHtml(m.name)}"><span>${escapeHtml((m.category || 'Rx').slice(0, 2).toUpperCase())}</span></button><div class="product-content"><p class="card-kicker">${escapeHtml(m.category || 'Medicine')}</p><h3>${escapeHtml(m.name)}</h3><p class="product-description">${escapeHtml(m.description || 'Reliable pharmacy care.')}</p><div class="product-footer"><strong>${money(m.price)}</strong><span class="stock ${m.stock > 0 ? '' : 'out'}">${m.stock > 0 ? `${m.stock} in stock` : 'Out of stock'}</span></div><button class="button button-small" data-add="${m.id}" ${m.stock < 1 ? 'disabled' : ''}>Add to cart</button></div></article>`).join(''); }
async function loadMedicines() { try { state.medicines = await request('/medicines'); const categories = [...new Set(state.medicines.map(m => m.category).filter(Boolean))].sort(); $('#category').innerHTML = '<option value="">All categories</option>' + categories.map(c => `<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join(''); renderCatalog(); } catch (error) { $('#catalog').innerHTML = ''; $('#catalog-empty').hidden = false; toast(error.message, true); } }
function openAuth(tab = 'login') { $('#auth-modal').hidden = false; switchAuthTab(tab); }
function switchAuthTab(tab) { document.querySelectorAll('[data-auth-tab]').forEach(button => button.classList.toggle('active', button.dataset.authTab === tab)); $('#login-form').hidden = tab !== 'login'; $('#register-form').hidden = tab !== 'register'; $('#auth-title').textContent = tab === 'login' ? 'Welcome back.' : 'Start with confidence.'; $('#auth-message').textContent = ''; }
function closeModal(id) { $(`#${id}`).hidden = true; }
function openDetail(id) { const medicine = state.medicines.find(item => item.id === Number(id)); if (!medicine) return; state.activeMedicine = medicine; $('#detail-category').textContent = medicine.category || 'Medicine'; $('#detail-title').textContent = medicine.name; $('#detail-description').textContent = medicine.description || 'Reliable pharmacy care.'; $('#detail-manufacturer').textContent = `By ${medicine.manufacturer || 'Apothecary Express'}`; $('#detail-prescription').textContent = medicine.prescriptionRequired ? 'Prescription required' : 'No prescription required'; $('#detail-price').textContent = money(medicine.price); $('#detail-quantity').max = medicine.stock; $('#detail-quantity').value = 1; $('#detail-add').disabled = medicine.stock < 1; $('#detail-modal').hidden = false; }
function addToCart(id, quantity = 1) { const medicine = state.medicines.find(item => item.id === Number(id)); if (!medicine || medicine.stock < 1) return; const existing = state.cart.find(item => item.medicine.id === medicine.id); const next = Math.min(medicine.stock, (existing?.quantity || 0) + Number(quantity)); if (existing) existing.quantity = next; else state.cart.push({ medicine, quantity: next }); renderCart(); toast(`${medicine.name} added to cart.`); }
function renderCart() { const count = state.cart.reduce((sum, item) => sum + item.quantity, 0); $('#cart-count').textContent = count; $('#cart-items').innerHTML = state.cart.length ? state.cart.map(item => `<div class="cart-item"><div><strong>${escapeHtml(item.medicine.name)}</strong><span>${money(item.medicine.price)} · ${item.quantity}</span></div><div class="cart-controls"><button data-cart-minus="${item.medicine.id}" aria-label="Decrease quantity">−</button><button data-cart-plus="${item.medicine.id}" aria-label="Increase quantity">+</button><button data-cart-remove="${item.medicine.id}" aria-label="Remove item">×</button></div></div>`).join('') : '<p class="empty-state">Your cart is waiting for something good.</p>'; $('#cart-total').textContent = money(state.cart.reduce((sum, item) => sum + item.medicine.price * item.quantity, 0)); $('#checkout').disabled = !state.cart.length; }
async function loadOrders() { if (!state.user) return openAuth(); try { const orders = await request(`/orders/user/${state.user.userId}`); $('#order-count').textContent = orders.length; $('#latest-status').textContent = orders[0]?.status || '—'; $('#order-list').innerHTML = orders.length ? orders.map(order => `<article class="order-row"><div><strong>Order #${Number(order.id)}</strong><span>${new Date(order.orderDate || Date.now()).toLocaleDateString()}</span></div><div><span>Medicine #${Number(order.medicineId)} · Qty ${Number(order.quantity)}</span><strong>${escapeHtml(order.status)}</strong></div><b>${money(order.totalPrice)}</b></article>`).join('') : '<p class="empty-state">No orders yet. Your next order will appear here.</p>'; } catch (error) { toast(error.message, true); } }
async function loadAdminMedicines() { try { const medicines = await request('/medicines'); $('#admin-medicines').innerHTML = medicines.map(m => `<div class="admin-row"><div><strong>${escapeHtml(m.name)}</strong><span>${escapeHtml(m.category)} · ${m.stock} in stock</span></div><div><button class="text-button" data-edit="${m.id}">Edit</button><button class="text-button danger" data-delete="${m.id}">Delete</button></div></div>`).join(''); await loadAdminOrders(); } catch (error) { toast(error.message, true); } }
async function loadAdminOrders() { try { const orders = await request('/orders'); $('#admin-orders').innerHTML = orders.length ? orders.map(order => `<article class="order-row"><div><strong>Order #${Number(order.id)}</strong><span>Customer #${Number(order.userId)}</span></div><div><span>Medicine #${Number(order.medicineId)} · Qty ${Number(order.quantity)}</span><strong>${escapeHtml(order.status)}</strong></div><b>${money(order.totalPrice)}</b></article>`).join('') : '<p class="empty-state">No orders to monitor.</p>'; } catch (error) { toast(error.message, true); } }
function logout(show = true) { sessionStorage.clear(); state.user = null; state.cart = []; updateAuthUi(); setView('catalog'); renderCart(); if (show) toast('You have been signed out.'); }
async function submitOrder() { if (!state.user) return openAuth(); const message = $('#cart-message'); message.textContent = ''; try { const orders = []; for (const item of state.cart) orders.push(await request('/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: state.user.userId, medicineId: item.medicine.id, quantity: item.quantity }) })); state.cart = []; renderCart(); closeCart(); await loadMedicines(); toast(`Order #${orders[0]?.id || ''} confirmed.`); setView('dashboard'); } catch (error) { message.textContent = error.message; toast(error.message, true); } }
document.addEventListener('click', event => { const target = event.target.closest('button'); if (!target) return; if (target.dataset.view) { if (target.dataset.view !== 'catalog' && !state.user) return openAuth(); setView(target.dataset.view); } if (target.dataset.detail) openDetail(target.dataset.detail); if (target.dataset.add) addToCart(target.dataset.add); if (target.dataset.authTab) switchAuthTab(target.dataset.authTab); if (target.dataset.close) closeModal(target.dataset.close); if (target.dataset.cartRemove) { state.cart = state.cart.filter(item => item.medicine.id !== Number(target.dataset.cartRemove)); renderCart(); } if (target.dataset.cartMinus || target.dataset.cartPlus) { const id = Number(target.dataset.cartMinus || target.dataset.cartPlus); const item = state.cart.find(entry => entry.medicine.id === id); if (item) item.quantity = Math.max(0, Math.min(item.medicine.stock, item.quantity + (target.dataset.cartPlus ? 1 : -1))); state.cart = state.cart.filter(item => item.quantity > 0); renderCart(); } if (target.dataset.edit) { const medicine = state.medicines.find(item => item.id === Number(target.dataset.edit)); if (medicine) { $('#edit-id').value = medicine.id; $('#medicine-name').value = medicine.name; $('#medicine-category').value = medicine.category; $('#medicine-manufacturer').value = medicine.manufacturer; $('#medicine-price').value = medicine.price; $('#medicine-stock').value = medicine.stock; $('#medicine-description').value = medicine.description || ''; $('#medicine-prescription').checked = medicine.prescriptionRequired; $('#medicine-save').textContent = 'Save changes'; $('#medicine-cancel').hidden = false; } } if (target.dataset.delete) deleteMedicine(target.dataset.delete); });
function closeCart() { $('#cart-drawer').classList.remove('open'); $('#cart-drawer').setAttribute('aria-hidden', 'true'); }
$('#auth-open').addEventListener('click', () => openAuth()); $('#hero-signin').addEventListener('click', () => openAuth()); $('#cart-open').addEventListener('click', () => { $('#cart-drawer').classList.add('open'); $('#cart-drawer').setAttribute('aria-hidden', 'false'); }); $('#cart-close').addEventListener('click', closeCart); $('#checkout').addEventListener('click', submitOrder); $('#logout').addEventListener('click', () => logout()); $('#refresh-orders').addEventListener('click', loadOrders); $('#refresh-admin-orders').addEventListener('click', loadAdminOrders); $('#search').addEventListener('input', renderCatalog); $('#category').addEventListener('change', renderCatalog); $('#sort').addEventListener('change', renderCatalog); $('#detail-add').addEventListener('click', () => { addToCart(state.activeMedicine.id, $('#detail-quantity').value); closeModal('detail-modal'); });
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); const message = $('#auth-message'); try { const data = await request('/users/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: $('#email').value, password: $('#password').value }) }); state.user = data; sessionStorage.setItem('user', JSON.stringify(data)); updateAuthUi(); closeModal('auth-modal'); toast(`Signed in as ${data.email}.`); } catch (error) { message.textContent = error.message; } });
$('#register-form').addEventListener('submit', async event => { event.preventDefault(); const message = $('#auth-message'); try { const data = await request('/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: $('#register-name').value, email: $('#register-email').value, password: $('#register-password').value, role: 'CUSTOMER' }) }); message.textContent = `Account created for ${data.email}.`; switchAuthTab('login'); $('#email').value = data.email; } catch (error) { message.textContent = error.message; } });
$('#medicine-form').addEventListener('submit', async event => { event.preventDefault(); const id = $('#edit-id').value; const body = { name: $('#medicine-name').value, description: $('#medicine-description').value, category: $('#medicine-category').value, price: Number($('#medicine-price').value), stock: Number($('#medicine-stock').value), prescriptionRequired: $('#medicine-prescription').checked, manufacturer: $('#medicine-manufacturer').value }; try { await request(id ? `/medicines/${id}` : '/medicines', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); resetMedicineForm(); await loadMedicines(); await loadAdminMedicines(); toast(id ? 'Medicine updated.' : 'Medicine added.'); } catch (error) { toast(error.message, true); } });
async function deleteMedicine(id) { if (!window.confirm('Remove this medicine from the catalog?')) return; try { await request(`/medicines/${id}`, { method: 'DELETE' }); await loadMedicines(); await loadAdminMedicines(); toast('Medicine removed.'); } catch (error) { toast(error.message, true); } }
function resetMedicineForm() { $('#medicine-form').reset(); $('#edit-id').value = ''; $('#medicine-save').textContent = 'Add medicine'; $('#medicine-cancel').hidden = true; }
$('#medicine-cancel').addEventListener('click', resetMedicineForm); updateAuthUi(); renderCart(); loadMedicines();
