spring.application.name=user-service

server.port=${PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/pharma_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health
jwt.secret=${JWT_SECRET}
bootstrap.admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
spring.cloud.compatibility-verifier.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration