create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(32) not null,
    constraint users_role_check check (role in ('CUSTOMER', 'ADMIN'))
);

create table if not exists medicines (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255),
    category varchar(255) not null,
    price numeric(12, 2) not null check (price >= 0),
    stock integer not null check (stock >= 0),
    prescription_required boolean not null default false,
    manufacturer varchar(255) not null
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    medicine_id bigint not null,
    quantity integer not null check (quantity > 0),
    total_price numeric(12, 2) not null check (total_price >= 0),
    status smallint not null check (status between 0 and 5),
    order_date timestamptz not null default current_timestamp
);

create unique index if not exists users_email_idx on users (email);
create index if not exists orders_user_id_idx on orders (user_id);
create index if not exists orders_medicine_id_idx on orders (medicine_id);
